---

- name: Configure servers with ruby support
  hosts: all
  sudo: yes
  vars_prompt:
    - name: "database_choice"
      prompt: "Please select database [postgresql/mysql]"
      private: no
  vars_files:
    - "vars/main.yml"
  vars:
    ubuntu_required_packages:
      - ufw
      - fail2ban
      - unattended-upgrades
    ubuntu_common_ssh_port: 41

  tasks:
    - name: Install required packages
      apt: state=installed pkg={{ item }}
      with_items: ubuntu_required_packages

    - name: Setup ufw
      ufw: state=enabled policy=deny

    - name: Allow ssh traffic
      ufw: rule=allow port={{ ubuntu_common_ssh_port }} proto=tcp

    - name: Allow web traffic
      ufw: rule=allow port=80

    - name: Change ssh port
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^Port\s"
                  line="Port {{ ubuntu_common_ssh_port }}"
                  state=present
      notify: Restart ssh

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh

    - name: Allow specify users
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^AllowUsers"
                  line="AllowUsers {{ username }}"
                  state=present
                  insertafter=EOF
      notify: Restart ssh
      
    - name: Set bash for user
      shell: "usermod -s /bin/bash {{ username }}"

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

  roles:
      - kun432.build-essential
      - geerlingguy.git
      - { role: ANXS.postgresql, tags: postgresql, when: database_choice == "postgresql"}
      - { role: ANXS.mysql, tags: mysql, when: database_choice == "mysql" }
      - cchurch.admin-users
      - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
      - geerlingguy.passenger
      - ANXS.monit
      - bennojoy.memcached
      - crushlovely.imagemagick
      - geerlingguy.redis
      # - agios.nginx-unicorn
      # - agios.unicorn-rvm