---

- name: Configure servers with ruby support
  hosts: all

  roles:
    - kun432.build-essential
    - geerlingguy.git
    - ANXS.postgresql
    - ANXS.mysql
    - cchurch.admin-users
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
    - geerlingguy.passenger
    - ANXS.monit
    - bennojoy.memcached
    - crushlovely.imagemagick
    - geerlingguy.redis