# file: build-essential/vars/Ubuntu.yml

buildessential_packages:
  - autoconf
  - binutils-doc
  - bison
  - build-essential
  - flex
  - gettext
  - libncurses5-dev
  - libxml2
  - libxml2-dev
  - libxslt1-dev
  - zlib1g-dev
