---
passenger_server_name: www.example.com
passenger_app_root: /opt/example/public
passenger_app_env: production

passenger_root: /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
passenger_ruby: /usr/local/rvm/rubies/ruby-2.1.3/bin/ruby # when we use ruby 2.1.3 and default dir '/usr/local/rvm/rubies'

nginx_worker_processes: "4"
nginx_worker_connections: "768"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
